version: '3.8'
services:

  securityserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'securityserver'
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/jwt_security
  db:
    container_name: db
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_PASSWORD = $DB_ROOT_PASSWORD
      - POSTGRES_USER = $DB_ROOT_USER
      - POSTGRES_DB = $DB_POSTGRES
